name: Docker Build

on:
  workflow_call:
    inputs:
      docker-registry:
        description: Docker registry
        default: ghcr.io
        required: false
        type: string
      docker-repo:
        description: Docker repository
        default: ${{ github.repository_owner }}
        required: false
        type: string
      docker-image:
        description: Docker image name
        required: true
        type: string
      docker-platform:
        description: Docker platform(s) to build for
        default: linux/amd64,linux/arm64
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: arm64
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        platforms: ${{ inputs.docker-platform }}
    - name: Login to Docker registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.docker-registry }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Set environment variables
      run: |
        DOCKER_TAG="${{ inputs.docker-registry }}/${{ inputs.docker-repo }}/${{ inputs.docker-image }}:${{ github.ref_name }}"
        if [ "${{ github.ref_type }}" != "tag" ]; then
          DOCKER_TAG="${DOCKER_TAG},${DOCKER_TAG}-$(date +'%Y%m%d-%H%M')-$(echo ${{ github.sha }} | head -c 7)"
        fi
        echo "DOCKER_TAG=${DOCKER_TAG,,}" >> "$GITHUB_ENV"
    - name: Build and push image
      uses: docker/build-push-action@v6
      with:
        tags: ${{ env.DOCKER_TAG }}
        platforms: ${{ inputs.docker-platform }}
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        labels: |
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
          org.opencontainers.image.url=${{ github.server_url }}/${{ github.repository }}
